services:
    app:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        container_name: php_import
        working_dir: /var/www
        volumes:
            - ./src:/var/www
        ports:
            - "5173:5173"
        networks:
            - importer

    web:
        image: nginx:alpine
        container_name: nginx_import
        working_dir: /var/www
        volumes:
            - ./src:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        ports:
            - "80:80"
        networks:
            - importer

networks:
    importer:
        driver: bridge
